"""Kagi search and summarization tools.

Search runs against the v1 public-preview API via httpx. Summarize remains
on the v0 surface via the legacy kagiapi client until the /summarize
endpoint lands on v1; the v0 helpers (`get_client`, `_extract_balance`,
`_check_balance`, `_summarize_locked`, `_handle_v0_error`) are dormant
load-bearing for that second tool and retire when the migration completes.
"""

import logging
from pathlib import Path
from typing import Annotated, Any, Literal, Optional

import httpx
from kagiapi import KagiClient
from pydantic import Field

from .common import _API_USER_AGENT, clean_env, tool_name
from .markdown import (
    FMEntries,
    _append_frontmatter_entry,
    _build_frontmatter,
    _fence_content,
    _TRUST_ADVISORY,
)

logger = logging.getLogger(__name__)

CONFIG_PATH = Path.home() / ".config" / "parkour" / "kagi_api_key"

_NO_KEY_MSG = (
    "Error: API key not found. "
    "Create ~/.config/parkour/kagi_api_key or set KAGI_API_KEY env var."
)

# ---------------------------------------------------------------------------
# v1 public-preview API
# ---------------------------------------------------------------------------

_V1_BASE = "https://kagi.com/api/v1"
_V1_TIMEOUT = 30.0

_WorkflowType = Literal["search", "images", "videos", "news", "podcasts"]

# Workflow → primary result key in the v1 response's data object.  Confirmed
# against the live endpoint: every workflow uses the singular form (video,
# not videos), and the workflow name in the request body uses the plural form
# (videos, not video).  data may carry additional secondary categories per
# workflow (video_creator, interesting_news, podcast_creator, infobox,
# related_search) — only related_search is surfaced here.
_WORKFLOW_RESULT_KEY: dict[str, str] = {
    "search": "search",
    "videos": "video",
    "news": "news",
    "images": "image",
    "podcasts": "podcast",
}
_VALID_WORKFLOWS = frozenset(_WORKFLOW_RESULT_KEY)

# Valid values for filters.region.  Generated by
# scripts/generate_kagi_regions.py from Kagi's regional bangs table at
# https://github.com/kagisearch/kagi-docs/blob/main/docs/kagi/features/bangs.md.
# Run that script when Kagi changes the region set.  `int` (International)
# is intentionally excluded: bangs lists it but the v1 search API rejects
# it for filters.region with search.filters_region_invalid.  The
# kagi://regions MCP resource publishes this mapping to callers.
# --- REGION_CODES (generated; do not edit between markers) ---
_REGION_CODES: dict[str, str] = {
    "at": "Austria",
    "be": "Belgium (en)",
    "be_fr": "Belgium (fr)",
    "bj": "Benin",
    "by": "Belarus",
    "bz": "Belize",
    "ca": "Canada (en)",
    "ca_fr": "Canada (fr)",
    "cf": "Central African Republic",
    "ch": "Switzerland (de)",
    "ch_fr": "Switzerland (fr)",
    "cn": "China",
    "co": "Colombia",
    "cx": "Christmas Island",
    "cy": "Cyprus",
    "de": "Germany",
    "dk": "Denmark",
    "es": "Spain (es)",
    "es_ca": "Spain (ca)",
    "fr": "France",
    "gb": "United Kingdom",
    "hr": "Croatia",
    "hu": "Hungary",
    "il": "Israel",
    "im": "Isle of Man",
    "in": "India",
    "iq": "Iraq",
    "ir": "Iran",
    "it": "Italy",
    "jp": "Japan",
    "ke": "Kenya",
    "ki": "Kiribati",
    "kw": "Kuwait",
    "ky": "Cayman Islands",
    "kz": "Kazakhstan",
    "lr": "Liberia",
    "ly": "Libya",
    "mg": "Madagascar",
    "my": "Malaysia",
    "nl": "Netherlands",
    "no": "Norway",
    "nz": "New Zealand",
    "om": "Oman",
    "pl": "Poland",
    "pt": "Portugal",
    "qa": "Qatar",
    "re": "Réunion",
    "rs": "Serbia",
    "si": "Slovenia",
    "tg": "Togo",
    "th": "Thailand",
    "tk": "Tokelau",
    "to": "Tonga",
    "ua": "Ukraine",
    "us": "United States",
    "uy": "Uruguay",
    "uz": "Uzbekistan",
    "vi": "U.S. Virgin Islands",
    "vn": "Vietnam",
    "vu": "Vanuatu",
    "ye": "Yemen",
    "za": "South Africa",
    "zm": "Zambia",
}
# --- END REGION_CODES ---

# Default Kagi lenses surfaced through kagi://lenses.  Generated by
# scripts/generate_kagi_lenses.py from
# https://github.com/kagisearch/kagi-docs/blob/main/docs/kagi/features/lenses.md.
# The lens_id sent to the v1 API is the lowercase display name, spaces
# preserved (`news 360`, `kagi documentation`).  Underscore variants
# (`kagi_documentation`) do NOT engage the lens — they fall back to a
# default search.  `always_on=False` entries require the user to enable
# the lens at https://kagi.com/settings/lenses; callers should treat them
# as "may not engage for this user".
# --- DEFAULT_LENSES (generated; do not edit between markers) ---
_DEFAULT_LENSES: list[dict[str, str | bool]] = [
    {"name": "Forums", "slug": "forums", "purpose": "search forums from around the web.", "always_on": True},
    {"name": "Programming", "slug": "programming", "purpose": "official programming language websites and forums.", "always_on": True},
    {"name": "News 360", "slug": "news 360", "purpose": "offers a 360-degree perspective on news impacting the globe.", "always_on": True},
    {"name": "Fediverse Forums", "slug": "fediverse forums", "purpose": "search Lemmy and kbin fediverse forums.", "always_on": True},
    {"name": "Usenet/Archive", "slug": "usenet/archive", "purpose": "search Usenet Archives and Archive.org non-web collections.", "always_on": True},
    {"name": "Academic", "slug": "academic", "purpose": "searches education (.edu) domains.", "always_on": True},
    {"name": "PDFs", "slug": "pdfs", "purpose": "search for PDF files.", "always_on": True},
    {"name": "Kagi Documentation", "slug": "kagi documentation", "purpose": "searches help.kagi.com, blog.kagi.com, kagifeedback.org, and orionfeedback.org.", "always_on": True},
    {"name": "Cyber Security", "slug": "cyber security", "purpose": "search cyber security news websites.", "always_on": False},
    {"name": "Small Web", "slug": "small web", "purpose": "results that favor noncommercial domains and topics.", "always_on": False},
    {"name": "Recipes", "slug": "recipes", "purpose": "recipes without spam from high-quality (English) recipe sites.", "always_on": False},
]
# --- END DEFAULT_LENSES ---


def kagi_lenses_markdown() -> str:
    """Render the default lens catalog for the kagi://lenses MCP resource."""
    always_on = [lens for lens in _DEFAULT_LENSES if lens["always_on"]]
    activation_gated = [lens for lens in _DEFAULT_LENSES if not lens["always_on"]]
    parts = [
        "# Kagi default lenses",
        "",
        "Built-in lens identifiers for `kagi_search`'s `lens_id` "
        "parameter. The slug is the lowercase display name with "
        "spaces preserved (`news 360`, `kagi documentation`). "
        "Underscore variants do not engage the lens — they fall back "
        "to a default search.",
        "",
        "User-created lenses are not enumerated here; their lens IDs "
        "come from `https://kagi.com/lenses/<id>` after the user "
        "marks the lens shareable at "
        "https://kagi.com/settings/lenses.",
        "",
        "## Always available",
        "",
    ]
    for lens in always_on:
        parts.append(f"- **{lens['name']}** (`{lens['slug']}`) — {lens['purpose']}")
    parts.extend([
        "",
        "## Require user activation",
        "",
        "These lenses must be enabled at "
        "https://kagi.com/settings/lenses by the account holder. "
        "Sending the slug for an unactivated lens falls back to a "
        "default search rather than erroring.",
        "",
    ])
    for lens in activation_gated:
        parts.append(f"- **{lens['name']}** (`{lens['slug']}`) — {lens['purpose']}")
    parts.append("")
    return "\n".join(parts)


def kagi_regions_markdown() -> str:
    """Render the valid region-code set for the kagi://regions MCP resource."""
    rows = "\n".join(
        f"| {code} | {name} |" for code, name in _REGION_CODES.items()
    )
    return (
        "# Kagi region codes\n\n"
        "Valid values for `kagi_search`'s `region` parameter. Codes are "
        "case-sensitive (lowercase only). Pins both region and result "
        "language; there is no separate language argument.\n\n"
        "Source: Kagi's regional bangs at "
        "https://help.kagi.com/kagi/features/bangs.html#regional-bangs. "
        "The `int` (international) bang from that list is intentionally "
        "absent — it's a valid bang in the Kagi UI but the v1 search "
        "API rejects it for `filters.region`. Omit the `region` argument "
        "to skip regional localization.\n\n"
        "| Code | Region |\n"
        "|------|--------|\n"
        f"{rows}\n"
    )


# ---------------------------------------------------------------------------
# v0 dormant island (powers summarize until /summarize lands on v1)
# ---------------------------------------------------------------------------

_LOW_BALANCE_THRESHOLD = 1.00  # dollars

# Session lockout for summarize. Flipped True by v0 responses with low
# balance; cleared by v0 responses with healthy balance on non-summarize
# calls. v1 search does not touch this — v1 dropped meta.api_balance.
_summarize_locked: bool = False


def _extract_balance(response: dict) -> Optional[float]:
    """Extract api_balance from a v0 Kagi response."""
    meta = response.get("meta", {})
    balance = meta.get("api_balance")
    if balance is not None:
        try:
            return float(balance)
        except (TypeError, ValueError):
            pass
    return None


def _check_balance(response: Any, is_summarize: bool = False) -> Optional[str]:
    """Check balance on a v0 response, update lockout state, return warning or None.

    Non-summarize calls clear the lockout if balance has recovered.
    """
    global _summarize_locked
    balance = _extract_balance(response)
    if balance is None:
        return None

    if balance < _LOW_BALANCE_THRESHOLD:
        _summarize_locked = True
        return (
            f"Kagi API balance low: ${balance:.2f} remaining. "
            f"Add funds at https://kagi.com/settings?p=billing"
        )
    else:
        if not is_summarize:
            _summarize_locked = False
        return None


def _handle_v0_error(e: Exception) -> str:
    """Format a kagiapi (v0) exception into a user-facing error string.

    v0 error envelope: ``{"error": [{"code": 101, "msg": "..."}]}``.
    requests.Response.__bool__ returns False for 4xx/5xx — compare with
    ``is not None``.
    """
    response = getattr(e, "response", None)
    status_code = getattr(response, "status_code", None)

    if response is not None:
        response_text = getattr(response, "text", None)
        if response_text:
            try:
                import json
                body = json.loads(response_text)
                errors = body.get("error") or []
                if errors and isinstance(errors, list):
                    kagi_msg = errors[0].get("msg", "")
                    if "Insufficient credit" in kagi_msg:
                        return "Error: Insufficient API credits. Add funds at https://kagi.com/settings?p=billing_api"
            except (json.JSONDecodeError, KeyError, IndexError):
                pass

    if status_code == 401:
        return "Error: Invalid API key. Check ~/.config/parkour/kagi_api_key or KAGI_API_KEY env var."
    if status_code == 402:
        return "Error: Insufficient API credits. Add funds at https://kagi.com/settings?p=billing_api"
    return f"Error: {e}"


def get_client() -> Optional[KagiClient]:
    """Create a Kagi v0 client. Used only by summarize until /summarize migrates."""
    api_key = get_api_key()
    if not api_key:
        return None
    return KagiClient(api_key=api_key)


# ---------------------------------------------------------------------------
# v1 error parser
# ---------------------------------------------------------------------------

def _handle_v1_error(e: Exception) -> str:
    """Format an httpx (v1) exception into a user-facing error string.

    v1 error envelope::

        {"errors": [{"code": "general.unauthorized",
                     "url": "https://kagi.com/api#todo",
                     "message": "Unauthorized"}]}

    Codes are dotted strings; the structural shape applies on all non-2xx
    responses observed so far.
    """
    if isinstance(e, httpx.TimeoutException):
        return "Error: Kagi API request timed out."

    if isinstance(e, httpx.HTTPStatusError):
        status_code = e.response.status_code
        try:
            body = e.response.json()
        except ValueError:
            body = None

        if isinstance(body, dict):
            errors = body.get("errors") or []
            if isinstance(errors, list) and errors:
                err = errors[0] if isinstance(errors[0], dict) else {}
                code = err.get("code") or ""
                message = err.get("message") or ""
                if code == "general.unauthorized":
                    return (
                        "Error: Invalid API key. "
                        "Check ~/.config/parkour/kagi_api_key or KAGI_API_KEY env var."
                    )
                if "insufficient_credit" in code or "billing" in code:
                    return (
                        "Error: Insufficient API credits. "
                        "Add funds at https://kagi.com/settings?p=billing_api"
                    )
                if message and code:
                    return f"Error: Kagi v1: {message} ({code})"
                if message:
                    return f"Error: Kagi v1: {message}"

        if status_code == 401:
            return (
                "Error: Invalid API key. "
                "Check ~/.config/parkour/kagi_api_key or KAGI_API_KEY env var."
            )
        if status_code == 402:
            return (
                "Error: Insufficient API credits. "
                "Add funds at https://kagi.com/settings?p=billing_api"
            )
        return f"Error: Kagi v1 returned HTTP {status_code}."

    if isinstance(e, httpx.RequestError):
        return f"Error: Kagi API request failed: {type(e).__name__}"

    return f"Error: {e}"


# ---------------------------------------------------------------------------
# Key handling (shared)
# ---------------------------------------------------------------------------

def get_api_key() -> str:
    """Load API key from config file or environment."""
    if key := clean_env("KAGI_API_KEY"):
        return key
    if CONFIG_PATH.exists():
        return CONFIG_PATH.read_text().strip()
    return ""


# ---------------------------------------------------------------------------
# v1 search
# ---------------------------------------------------------------------------

def _format_result_line(item: dict) -> str:
    """Format a single v1 result item as ``[title](url) - snippet (time)``.

    Snippet and time are optional and omitted cleanly when absent (image
    workflow items lack snippet, infobox items lack time).
    """
    title = item.get("title", "Untitled")
    item_url = item.get("url", "")
    snippet = item.get("snippet", "")
    published = item.get("time")
    line = f"[{title}]({item_url})"
    if snippet:
        line += f" - {snippet}"
    if published:
        line += f" ({published})"
    return line


async def search(
    query: Annotated[str, Field(
        description=(
            "Search query string. Supports operators: site:example.com "
            "(restrict to a domain), filetype:pdf (restrict to a file "
            "type), intitle:term (match in page title), inurl:term "
            '(match in URL), "exact phrase" (exact match), '
            "+term / -term (require / exclude), (A AND B) / (A OR B) "
            "(boolean grouping), * (wildcard word substitution)."
        ),
    )],
    limit: Annotated[int, Field(
        description=(
            "Maximum number of results returned per page. Default 5; "
            "max 1024. limit is always the page size — when 'page' is "
            "omitted you implicitly receive page 1. Caps the response "
            "count only — Kagi picks its top hits internally, so a "
            "smaller limit returns the best of the same ranking, not "
            "a different ranking. Applies across all workflows."
        ),
        ge=1, le=1024,
    )] = 5,
    *,
    workflow: Annotated[Optional[_WorkflowType], Field(
        description=(
            "Result category. Omit for 'search' (web results with "
            "related-query suggestions). Other workflows surface only "
            "their named primary category: 'images' returns image "
            "hits, 'videos' returns video hits, 'news' returns news "
            "articles, 'podcasts' returns podcast episodes."
        ),
    )] = None,
    lens_id: Annotated[Optional[str], Field(
        description=(
            "Kagi Lens to apply. A lens is a stored search profile "
            "that scopes the query (sites, keywords, file type, "
            "region, time window) before any filters set here take "
            "effect. Designed for the default 'search' workflow; on "
            "other workflows the lens may be silently ignored or may "
            "filter results to empty. Unknown slugs are not rejected "
            "— they fall back silently to results that ignore the "
            "lens, so the response cannot confirm the lens engaged. "
            "The 'region', 'after', and 'before' parameters override "
            "the lens's equivalents when both are supplied. Accepted "
            "forms: a built-in lens slug (lowercase display name with "
            "spaces preserved; always-available slugs are 'forums', "
            "'programming', 'news 360', 'fediverse forums', "
            "'usenet/archive', 'academic', 'pdfs', 'kagi "
            "documentation' — note that 'news 360' is a web-search "
            "lens distinct from the 'news' workflow), a shareable "
            "lens ID (the ID portion of https://kagi.com/lenses/<id>), "
            "or the full lens URL. User-created lenses have no "
            "programmatic discovery path — pass null unless the user "
            "has handed you one."
        ),
    )] = None,
    page: Annotated[Optional[int], Field(
        description=(
            "Page number, 1-indexed (1..10). Page size is 'limit'; max "
            "practical reach is page × limit. Pagination is not strict "
            "offset — adjacent pages can share some URLs, so deduplicate "
            "downstream when consuming multiple pages. Repeated calls to "
            "the same page return identical results in identical order. "
            "Deep paging needs a larger 'limit' — at the default limit=5, "
            "page=10 only reaches ~result 50. Omit (or pass null) for "
            "the first page. Applies across all workflows."
        ),
        ge=1, le=10,
    )] = None,
    region: Annotated[Optional[str], Field(
        description=(
            "Lowercase Kagi region code (case-sensitive — 'us', not "
            "'US'). Codes include lowercase ISO 3166-1 alpha-2 forms "
            "like 'us', 'de', 'jp', plus language-suffix variants for "
            "multilingual countries like 'ca_fr' (Canada in French). "
            "Bad codes (unknown values, wrong case) return HTTP 400 "
            "with a structured error — the filter never silently "
            "degrades. Pins both region and result language; there is "
            "no separate language argument. Effectiveness varies by "
            "workflow — strongest on web search and news, weak or "
            "absent on images. Omit to skip regional localization. "
            "Overrides lens_id's region."
        ),
    )] = None,
    after: Annotated[Optional[str], Field(
        description=(
            "ISO 8601 date 'YYYY-MM-DD' (e.g. '2025-01-01'). Returns "
            "only results published or updated on or after this date. "
            "Results that lack a detectable date are silently excluded "
            "— on workflows where results commonly carry no date "
            "('images' especially), this filter can produce few or no "
            "results. Overrides any date floor carried by 'lens_id'."
        ),
    )] = None,
    before: Annotated[Optional[str], Field(
        description=(
            "ISO 8601 date 'YYYY-MM-DD' (e.g. '2025-12-31'). Returns "
            "only results published or updated on or before this date. "
            "Results that lack a detectable date are silently excluded "
            "— on workflows where results commonly carry no date "
            "('images' especially), this filter can produce few or no "
            "results. Overrides any date ceiling carried by 'lens_id'."
        ),
    )] = None,
) -> str:
    """Search the web using Kagi's curated v1 search index."""
    api_key = get_api_key()
    if not api_key:
        return _NO_KEY_MSG

    if workflow is not None and workflow not in _VALID_WORKFLOWS:
        return (
            f"Error: Invalid workflow {workflow!r}. "
            f"Must be one of: {', '.join(sorted(_VALID_WORKFLOWS))}."
        )

    if page is not None and not 1 <= page <= 10:
        return f"Error: page must be between 1 and 10 (got {page})."

    body: dict[str, Any] = {"query": query, "limit": limit}
    if workflow is not None:
        body["workflow"] = workflow
    if lens_id is not None:
        body["lens_id"] = lens_id
    if page is not None:
        body["page"] = page

    filters: dict[str, Any] = {}
    if region:
        filters["region"] = region
    if after:
        filters["after"] = after
    if before:
        filters["before"] = before
    if filters:
        body["filters"] = filters

    headers = {
        "User-Agent": _API_USER_AGENT,
        "Accept": "application/json",
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    try:
        async with httpx.AsyncClient(timeout=_V1_TIMEOUT) as client:
            resp = await client.post(
                f"{_V1_BASE}/search",
                headers=headers,
                json=body,
            )
            resp.raise_for_status()
    except Exception as e:
        logger.exception("Error during v1 search")
        return _handle_v1_error(e)

    try:
        response = resp.json()
    except ValueError:
        return "Error: Unexpected response format from Kagi v1 search."

    data = response.get("data") or {}
    if not isinstance(data, dict):
        return "Error: Unexpected response format from Kagi v1 search."

    # v1 returns category-keyed arrays under data, not the v0 t-coded flat
    # list. The primary category depends on workflow; related_search is the
    # search-workflow companion (other workflows have their own secondary
    # arrays like video_creator/interesting_news that we skip here).
    primary_key = _WORKFLOW_RESULT_KEY.get(workflow or "search", "search")
    primary_items = data.get(primary_key, [])
    related_items = data.get("related_search", [])

    results: list[str] = [
        _format_result_line(item)
        for item in primary_items
        if isinstance(item, dict)
    ]

    related_titles = [
        r.get("title", "")
        for r in related_items
        if isinstance(r, dict) and r.get("title")
    ]

    output_parts: list[str] = []
    if results:
        output_parts.append("Results:")
        for i, result in enumerate(results, 1):
            output_parts.append(f"{i}. {result}")
    else:
        output_parts.append("No results found.")

    if related_titles:
        output_parts.append("")
        output_parts.append(f"Related searches: {', '.join(related_titles)}")

    content = "\n".join(output_parts)

    fm_entries = FMEntries({
        "source": f"kagi {workflow or 'search'}: {query}",
        "trust": _TRUST_ADVISORY,
    })

    if lens_id is not None and workflow is not None and workflow != "search":
        _append_frontmatter_entry(
            fm_entries, "warning",
            f"lens_id is unreliable on workflow={workflow!r}; may be "
            "silently ignored or filter results to empty. The lens is "
            "designed for the default 'search' workflow. Retry without "
            "lens_id to compare.",
        )

    if region is not None and workflow == "images":
        _append_frontmatter_entry(
            fm_entries, "warning",
            "region has no visible effect on workflow='images'; the "
            "result set will match the unlocalized search.",
        )

    if (after is not None or before is not None) and workflow == "images":
        _append_frontmatter_entry(
            fm_entries, "warning",
            "'images' results typically lack date metadata; after/"
            "before may not engage and the result set will be smaller "
            "or empty.",
        )

    if results:
        _append_frontmatter_entry(
            fm_entries, "hint",
            f"Drill into a result URL with {tool_name('web_fetch_sections')} "
            f"to scout layout, or {tool_name('web_fetch_direct')} for body content.",
        )
    else:
        active_filters: list[str] = []
        if lens_id is not None:
            active_filters.append(f"lens_id={lens_id!r}")
        if region is not None:
            active_filters.append(f"region={region!r}")
        if after is not None:
            active_filters.append(f"after={after!r}")
        if before is not None:
            active_filters.append(f"before={before!r}")
        if active_filters:
            _append_frontmatter_entry(
                fm_entries, "hint",
                f"No results with active filters: {', '.join(active_filters)}. "
                "Retry without the most restrictive filter to localize the "
                "cause.",
            )
        else:
            _append_frontmatter_entry(
                fm_entries, "hint",
                'Widen the query: drop site: or filetype: qualifiers, quote '
                'phrases as "exact match", or replace +required terms with '
                "looser alternatives.",
            )

    fm = _build_frontmatter(fm_entries)
    return fm + "\n\n" + _fence_content(content)


# ---------------------------------------------------------------------------
# v0 summarize (dormant; unregistered until /summarize lands on v1)
# ---------------------------------------------------------------------------

async def summarize(
    url: Optional[str] = None,
    text: Optional[str] = None,
    summary_type: Literal["summary", "takeaway"] = "summary"
) -> str:
    """Summarize content from a URL or text using Kagi's Universal Summarizer.

    Supports web pages, PDFs, YouTube videos, audio files, and documents.
    Use this when WebFetch fails due to agent blacklisting or access restrictions.

    Args:
        url: URL to summarize (PDFs, YouTube, articles, audio)
        text: Raw text to summarize (alternative to url)
        summary_type: Output format - "summary" for prose, "takeaway" for bullet points
    """
    if _summarize_locked:
        return (
            "Error: kagi_summarize is temporarily disabled due to low API balance. "
            "Summarization requests are expensive and the remaining balance may not "
            "cover the cost. Use a kagi_search call to recheck the balance, or add "
            "funds at https://kagi.com/settings?p=billing"
        )

    client = get_client()
    if not client:
        return _NO_KEY_MSG

    if not url and not text:
        return "Error: Either 'url' or 'text' must be provided."

    if url and text:
        return "Error: Provide either 'url' or 'text', not both."

    if summary_type not in ("summary", "takeaway"):
        return "Error: summary_type must be 'summary' or 'takeaway'."

    try:
        if url:
            response = client.summarize(url=url, summary_type=summary_type, target_language="EN")
        else:
            assert text is not None  # guarded by earlier url/text validation
            response = client.summarize(text=text, summary_type=summary_type, target_language="EN")
    except Exception as e:
        logger.exception("Error during summarization")
        return _handle_v0_error(e)

    # Extract summary
    content = response.get("data", {}).get("output", "")

    if not content:
        return "Error: No summary returned from API."

    fm_entries = FMEntries({
        "source": url or "text input",
        "trust": _TRUST_ADVISORY,
    })
    balance_warning = _check_balance(response, is_summarize=True)
    if balance_warning:
        fm_entries["balance_warning"] = balance_warning

    if url:
        _append_frontmatter_entry(
            fm_entries, "hint",
            f"To recover specifics the summary discarded, pass the same "
            f"URL to {tool_name('web_fetch_direct')} with section= or "
            "search= for targeted retrieval.",
        )

    fm = _build_frontmatter(fm_entries)
    return fm + "\n\n" + _fence_content(content)
