"""Performance regression tests for the parkour-mcp content pipeline.

These tests load gzip-compressed HTML fixtures from ``tests/fixtures/perf/``
and assert that each pipeline phase (``html_to_markdown``, ``MarkdownSplitter``,
``_extract_sections_from_markdown``, ``_compute_slice_ancestry``, tantivy
index build) runs within a multiplier of the captured baseline.

Baselines live at ``scripts/benchmark_baselines.json`` and are regenerated by
``uv run python3 scripts/benchmark_pipeline.py --update-baselines``.  Fixtures
are regenerated alongside baselines with ``--capture-fixtures``.

Tests are marked with ``@pytest.mark.perf`` and deselected by default.  Run
with ``uv run pytest -m perf`` or ``just test-perf``.

Tolerance strategy: phase-level wall clock is asserted against ``baseline *
tolerance``, where tolerance is 2.0 by default and can be overridden via the
``PERF_TOLERANCE`` env var.  Hardware variance between the baseline capture
machine (Apple Silicon per ``benchmark_baselines.json:hardware``) and the test
runner can easily land between 1.2x and 1.8x, so 2.0x is a deliberately loose
floor that catches order-of-magnitude regressions without flaking on normal
variance.
"""
import gzip
import json
import os
import time
from collections.abc import Callable
from pathlib import Path

import pytest
import tantivy
from semantic_text_splitter import MarkdownSplitter

from parkour_mcp.markdown import (
    _compute_slice_ancestry,
    _extract_sections_from_markdown,
    html_to_markdown,
)

pytestmark = pytest.mark.perf


# ---------------------------------------------------------------------------
# Fixture and baseline loading
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).parent.parent
FIXTURES_DIR = REPO_ROOT / "tests" / "fixtures" / "perf"
BASELINES_PATH = REPO_ROOT / "scripts" / "benchmark_baselines.json"


def _load_baselines() -> dict:
    if not BASELINES_PATH.exists():
        pytest.skip(
            f"{BASELINES_PATH.relative_to(REPO_ROOT)} not found — "
            "run `just benchmark --update-baselines` to generate",
        )
    with open(BASELINES_PATH) as f:
        return json.load(f)


BASELINES = _load_baselines()
TOLERANCE = float(os.environ.get("PERF_TOLERANCE", "2.0"))

SPLITTER = MarkdownSplitter((1600, 2000))


def _load_html(filename: str) -> str:
    path = FIXTURES_DIR / filename
    if not path.exists():
        pytest.skip(
            f"Fixture {path.relative_to(REPO_ROOT)} not found — "
            "run `just benchmark --capture-fixtures` to generate",
        )
    with gzip.open(path, "rt", encoding="utf-8") as f:
        return f.read()


def _time_ms(callable_fn: Callable[[], object], best_of: int = 1) -> float:
    """Run *callable_fn* and return elapsed time in milliseconds.

    When ``best_of > 1``, runs the callable *best_of* times and returns the
    minimum wall time.  This absorbs GC/allocator/scheduling noise that would
    otherwise cause flaky assertions on short-running phases.
    """
    best = float("inf")
    for _ in range(best_of):
        t0 = time.perf_counter()
        callable_fn()
        elapsed = (time.perf_counter() - t0) * 1000
        best = min(best, elapsed)
    return best


def _assert_under(elapsed_ms: float, baseline_ms: float, phase: str) -> None:
    limit = baseline_ms * TOLERANCE
    assert elapsed_ms < limit, (
        f"{phase} took {elapsed_ms:.0f}ms, baseline {baseline_ms:.0f}ms "
        f"(x{TOLERANCE} tolerance = {limit:.0f}ms)"
    )


def _build_tantivy(slices: list[str]) -> None:
    """Mirror of ``_CacheEntry`` tantivy index build for phase-level timing."""
    builder = tantivy.SchemaBuilder()
    builder.add_text_field("body", stored=True)
    builder.add_unsigned_field("idx", stored=True)
    schema = builder.build()
    index = tantivy.Index(schema)
    writer = index.writer()
    for i, text in enumerate(slices):
        writer.add_document(tantivy.Document(body=text, idx=i))
    writer.commit()
    index.reload()


# ---------------------------------------------------------------------------
# Shared per-tier fixture: decompress HTML once per test module
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def small_html() -> str:
    return _load_html("pep_8.html.gz")


@pytest.fixture(scope="module")
def medium_html() -> str:
    return _load_html("ecma262.html.gz")


@pytest.fixture(scope="module")
def pathological_html() -> str:
    return _load_html("whatwg_html.html.gz")


# ---------------------------------------------------------------------------
# Phase: html_to_markdown
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("tier,fixture_name", [
    ("small", "small_html"),
    ("medium", "medium_html"),
    ("pathological", "pathological_html"),
])
def test_html_to_markdown(tier: str, fixture_name: str, request: pytest.FixtureRequest) -> None:
    html = request.getfixturevalue(fixture_name)
    baseline = BASELINES["generic_http"][tier]["html_to_markdown_ms"]

    # Warm-up run to amortize any one-shot import/allocator costs that the
    # baseline capture pays for itself.
    html_to_markdown(html)

    elapsed_ms = _time_ms(lambda: html_to_markdown(html))
    _assert_under(elapsed_ms, baseline, f"html_to_markdown({tier})")


# Lower bound multiplier for the md_bytes truncation guard.  Any output
# smaller than this fraction of the captured baseline fails the test.  Set
# wide enough to absorb normal htmd rendering drift between patch releases
# (a few percent on well-formed HTML) and strict enough to catch the
# catastrophic-loss failure mode — kreuzberg 3.1.0 dropped WHATWG output
# from 6,338 KB to 425 KB (93% loss) while passing timing assertions.
_MD_BYTES_LOWER_BOUND = 0.75


@pytest.mark.parametrize("tier,fixture_name", [
    ("small", "small_html"),
    ("medium", "medium_html"),
    ("pathological", "pathological_html"),
])
def test_html_to_markdown_output_size(
    tier: str, fixture_name: str, request: pytest.FixtureRequest,
) -> None:
    """Guard against silent content truncation in ``html_to_markdown``.

    Timing assertions are structurally blind to "faster but wrong" failures
    where a converter regression drops most of the document: less content is
    cheaper to process, so a catastrophic truncation can pass a pure timing
    check without firing.  The kreuzberg 3.1.0 regression that motivated the
    htmd-py port (commit ``da4f54a``) is the canonical example — it produced
    425 KB of markdown on the 15 MB WHATWG spec vs htmd-py's 7,853 KB, a 93%
    content loss that read as "successful conversion" to any caller checking
    only elapsed time or exit status.

    This test asserts that ``len(markdown)`` stays at or above
    ``_MD_BYTES_LOWER_BOUND`` (0.75) times the captured baseline.  Upper
    bound is intentionally not checked: it would flake on legitimate
    rendering improvements in htmd (e.g. table alignment changes that add
    whitespace) without catching any failure mode the timing assertions
    wouldn't already catch.
    """
    html = request.getfixturevalue(fixture_name)
    baseline_bytes = BASELINES["generic_http"][tier]["md_bytes"]
    lower_bound = int(baseline_bytes * _MD_BYTES_LOWER_BOUND)

    _, markdown = html_to_markdown(html)
    actual_bytes = len(markdown)

    assert actual_bytes >= lower_bound, (
        f"html_to_markdown({tier}) produced {actual_bytes} bytes, "
        f"below truncation guard {lower_bound} "
        f"({_MD_BYTES_LOWER_BOUND}x baseline {baseline_bytes})"
    )


# ---------------------------------------------------------------------------
# Phase: MarkdownSplitter + section extraction + ancestry + tantivy
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def small_markdown(small_html: str) -> str:
    _, md = html_to_markdown(small_html)
    return md


@pytest.fixture(scope="module")
def medium_markdown(medium_html: str) -> str:
    _, md = html_to_markdown(medium_html)
    return md


@pytest.fixture(scope="module")
def pathological_markdown(pathological_html: str) -> str:
    _, md = html_to_markdown(pathological_html)
    return md


@pytest.mark.parametrize("tier,md_fixture", [
    ("small", "small_markdown"),
    ("medium", "medium_markdown"),
    ("pathological", "pathological_markdown"),
])
def test_splitter(tier: str, md_fixture: str, request: pytest.FixtureRequest) -> None:
    markdown = request.getfixturevalue(md_fixture)
    baseline = BASELINES["generic_http"][tier]["splitter_ms"]

    # Skip assertion for trivially-fast phases — ms-level noise makes
    # tolerance checks meaningless and the baseline itself may be < 1 ms.
    if baseline < 5.0:
        pytest.skip(f"baseline {baseline:.2f}ms too small for reliable assertion")

    elapsed_ms = _time_ms(lambda: SPLITTER.chunk_indices(markdown))
    _assert_under(elapsed_ms, baseline, f"MarkdownSplitter({tier})")


@pytest.mark.parametrize("tier,md_fixture", [
    ("small", "small_markdown"),
    ("medium", "medium_markdown"),
    ("pathological", "pathological_markdown"),
])
def test_extract_sections(tier: str, md_fixture: str, request: pytest.FixtureRequest) -> None:
    markdown = request.getfixturevalue(md_fixture)
    baseline = BASELINES["generic_http"][tier]["sections_ms"]

    if baseline < 5.0:
        pytest.skip(f"baseline {baseline:.2f}ms too small for reliable assertion")

    elapsed_ms = _time_ms(lambda: _extract_sections_from_markdown(markdown))
    _assert_under(elapsed_ms, baseline, f"_extract_sections_from_markdown({tier})")


@pytest.mark.parametrize("tier,md_fixture", [
    ("small", "small_markdown"),
    ("medium", "medium_markdown"),
    ("pathological", "pathological_markdown"),
])
def test_tantivy_index(tier: str, md_fixture: str, request: pytest.FixtureRequest) -> None:
    markdown = request.getfixturevalue(md_fixture)
    baseline = BASELINES["generic_http"][tier]["tantivy_ms"]

    chunks = SPLITTER.chunk_indices(markdown)
    slices = [text for _, text in chunks]

    # Warm-up: tantivy's first build in a process pays module init
    _build_tantivy(slices)

    if baseline < 5.0:
        pytest.skip(f"baseline {baseline:.2f}ms too small for reliable assertion")

    # Tantivy has high allocator variance on index builds — observed range
    # 24-230ms on the 5k-slice WHATWG workload across identical back-to-back
    # runs.  Take the best of 5 runs to absorb noise.
    elapsed_ms = _time_ms(lambda: _build_tantivy(slices), best_of=5)
    _assert_under(elapsed_ms, baseline, f"tantivy_index({tier})")


# ---------------------------------------------------------------------------
# Phase: full pipeline (html_to_markdown + splitter + sections + ancestry + tantivy)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("tier,fixture_name", [
    ("small", "small_html"),
    ("medium", "medium_html"),
    ("pathological", "pathological_html"),
])
def test_full_pipeline(tier: str, fixture_name: str, request: pytest.FixtureRequest) -> None:
    """Assert total generic-HTTP phase time stays near the sum of baselines.

    Catches regressions where an individual phase might stay within tolerance
    but their combined regression drifts the overall pipeline time upward.
    """
    html = request.getfixturevalue(fixture_name)
    b = BASELINES["generic_http"][tier]
    baseline_total_ms = (
        b["html_to_markdown_ms"]
        + b["splitter_ms"]
        + b["sections_ms"]
        + b["ancestry_ms"]
        + b["tantivy_ms"]
    )

    def _run_pipeline() -> None:
        _, markdown = html_to_markdown(html)
        chunks = SPLITTER.chunk_indices(markdown)
        slices = [text for _, text in chunks]
        offsets = [offset for offset, _ in chunks]
        sections = _extract_sections_from_markdown(markdown)
        _compute_slice_ancestry(sections, offsets)
        _build_tantivy(slices)

    # Warm-up amortizes one-shot costs the baseline capture paid for itself
    # (notably tantivy's first-build module init). best_of=5 then absorbs
    # tantivy's documented per-build allocator variance (24-230ms back-to-
    # back on the large workload); a single-shot measurement leaked that
    # noise into a flaky small-tier assertion against a 28ms tolerance.
    _run_pipeline()
    elapsed_ms = _time_ms(_run_pipeline, best_of=5)
    _assert_under(elapsed_ms, baseline_total_ms, f"full_pipeline({tier})")
